### ISSUE TITLE
My first look at the slider!

### ISSUE THREAD

**Issue by kmatch98** [jposada202020/CircuitPython_slider#1]
@jposada202020 This is a really cool. It really responds to the finger pretty fast!  Here are my comments.  Sorry if it looks like a lot of things, most are minor tweaks, I think the main question is about I expected the slider should respond to touch, and that's open for discussion.

----------
**graphics:** The slider can go outside the background box’s range, if slid all the way to the right side.

**touch behavior:**  The slider does not “center” on the touch point.  I have some touch-calibration error on my screen, but I think there is some offset in the code.

**touch action:**  For sliders, I think the touch-response should be as follows:
1.  Must first receive a “touch_down” within the touch_boundary.

2.  If touch is kept down, any “touch_move” actions will cause the slider to change values, even if the touchpoint is outside of the touch_boundary.
     - (Optional bonus behavior) The farther away the finger is from the slider, the “slower” the reaction.  That means, that you can be more accurate if you touch the slider, then move your finger vertically down, and then the slider can be placed more accurately when your finger is farther away.  I think this behavior is used on sliders for videos, and I appreciate it if you are trying to adjust the slider precisely.  Maybe this could have a “gain” option to adjust the sensitivity based on vertical distance from the slider.

3. When the touch is released from the screen, the slider must be directly touched again to go back to #1.

Implementation: If you implement the behavior above, I think you will need a state variable to track whether the slider has received a “touch_down” event.  To clear the state variable, I think you will need to create a “touch_up” Control function to let the slider know when it is released.

**function names:**  I recommend changing the `when_inside` command and renaming it to the `contains` boolean function.  Then your while loop can use:
```python
if p:
    if my.slider.contains(p): 
        my_slider.touch_down(p) # let the slider know it has been touched down 
    my_slider.touch_move(p) # handle any touch movements if the slider is still touched down
else: 
    my_slider.touch_up(p) # let the slider know it has been released

```
Another option is to add a public state variable so you can check the slider's "touch" state.  That way you could selectively call `touch_move` only when the "touch" state is "down".  Not sure if that's better or worse than the above code suggestion.

**touch boundary:** I think that more padding should be available at the “bottom” of the slider than the top.  When you touch the slider, you want to still be able to see the slider above your finger.  So your finger’s touchpoint will likely be “below” the slider.  I think it will be useful to have an option for non-uniform touch_padding.  I suggest including some default bottom_touch_padding since that would be expected by the user.

**simpletest example:** The slider is really small on my pyPortal.  Maybe make it a bit larger.

**value:** I think the value should default to be a float between 0 and 1.0.  Or the min/max value could be set during the initialization, similar to what I think is done in the progress bar.

**Comment by jposada202020** [comment]
@kmatch98 Thanks for the feedback, Good Points, I will work on this for sure, once I finish the libraries documentation :). Thanks Again, one thing make my laugh, the comment about the slow down, I know you have that in the widgets, but the first comes to mind, was a second degree differential equation of a spring in oil. 🔢  . Thanks

**Comment by kmatch98** [comment]
I'm thinking about the touch-response some more and maybe what I said above needs to be updated.  I don't think the simple code that I put above will work right in the case if you have multiple sliders.  

We need to handle a situation where one slider receives a "touch_down" and then any other sliders (or other widgets for that matter) should not be triggered with touch events until the slider gets the "touch_up".

I suspect @foamyguy has some experience with this.  Do you think that the event loop should handle which widget should have the "focus"?  For example, once we first touch a slider, we should only send "touch_move" commands to slider, until the next "touch_up" (when finger is released from the screen).  

Should this be handled by the event loop, or should each widget need to have the right state variables to understand whether it has focus.  

Here's a suggestion:
- The main event loop should keep track of the full "touch_down"->"touch_move"->"touch_up" cycle.  (This means that the event loop must first send a "touch_down" signal before ever sending a "touch_move" or "touch_up".)  The event loop needs to keep track of which "touch_*" state it is in.  But it doesn't need to keep track of which widget should have "focus".  It will keep sending these signals to all widgets and widgets have to decide if they have "focus".
- The widget should keep track if it received a "touch_down" response.
- The widget should only respond to "touch_move" or "touch_up" if it already received a "touch_down" response.

This is just a general concept (of course you could develop weird widgets that don't follow this exactly).

Your thoughts are welcome.

**Comment by jposada202020** [comment]
@kmatch98 Interesting.... I did this in a different way in the past... as we are merging MP, I would like to see if we could use some of the new features introduced. Meaning, For me as it is, you would have an event loop, meaning, what you said, the main code will verify, but we add all the widgets to an event loop and all will get updated at the same time, instead have them async. 

I agree with you, this discussion is very important, not only for this, but for all the widget development, we need to establish some kind of design rules.  Our purpose here will be maintainability, easy of support, easy of maintainability and the most important that for the user will be as easy as to say 
```python
if widget.touch:
   ...do something
```
Proposal lets copy paste this comments to the graphics team, you know I am down for whatever is easier for the user, and it would be easier in the future to add more features. 

I am a superfan of the text parameter keywords, because, if matplotlib taught us something is you always want to add more feature, and the enum thing restrict this, at least make it more difficult.  But I understand why people like their ENUMS :)

After all this discussion, could you re-post this comments in the graphics team, I could do it, but do not want to do this without your approval

**Comment by FoamyGuy** [comment]
Most of the systems I have experience with use some sort of callback type system for UI related events. I'm wondering if something like that might be possible with the new features from Micropython, but I am not sure.

In the absence of true callbacks. I do think having the logic in some sort of main event loop is probably the best way to go. I think What @TG-Techie has done with [TG-Gui](https://github.com/TG-Techie/TG-Gui-Core) is great. Perhaps we should be working toward making our widgets compatible with this system. I'm not 100% how it handles "touch move" type actions, but I'm pretty sure it can, because I think I recall TG-Techie showing a sliding selector widget example on a stream one day.

**Comment by jposada202020** [comment]
That is a good idea. I recall seeing somewhere too, maybe twitter... but yes you are right. I remember he mentions something about the event loop. Regarding the MP depending on what they decide to merge. Anyway as you said, we know now, that what TG does.  works so we could build from that.

**Comment by jposada202020** [comment]
@kmatch98 I started working on this, I have a list of the TODO, and I will add more items on your list until completed, 
one thing however is my intention with this was not have touch and move, so maybe the name is incorrect and we need to change it. my intention is use it like a volume up volume down in a computer, you just click where you want your level. It is clear that you can also touch and move but normally you just click. To think about, depending how difficult it is 😄 to implement
![image](https://user-images.githubusercontent.com/34255413/117222589-ca642000-add9-11eb-8905-8dcc12fc7c30.png)

Changes in #2
